name: Deploy to Bluehost

on:
  push:
    branches:
      - main # Change this to your default branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build Project
        run: npm run build

      - name: 📂 Sync files to Bluehost
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # The local folder to upload. 
          # For static export, we upload the 'out' folder created by 'npm run build'
          local-dir: ./out/
          # The remote folder on Bluehost
          server-dir: public_html/website_762482e9/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
